{% set name = "yaqd-seabreeze" %}
{% set version = "2021.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d40f8fa5d114c13c7038e74959d078b16c6d882b9712fb85b574bb358b2b6fa

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-seabreeze = yaqd_seabreeze._seabreeze:Seabreeze.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - flit
    - numpy
    - pyusb
    - seabreeze
    - yaqd-core >=2020.06.3
  run:
    - python >=3.7
    - numpy
    - pyusb
    - seabreeze
    - yaqd-core >=2020.06.3

test:
  imports:
    - yaqd_seabreeze
  commands:
    - pip check
    - yaqd-seabreeze --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for Ocean Optics SeaBreeze spectrometers.
  dev_url: https://gitlab.com/yaq/yaqd-seabreeze
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
