{% set name = "yaqd-seabreeze" %}
{% set version = "2025.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dba7d378753d6e562ad805c7e4e5414b96d9da09d33bb170d19682a28212a40c

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-seabreeze = yaqd_seabreeze._seabreeze:Seabreeze.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - flit
    - numpy
    - pyusb
    - seabreeze
    - yaqd-core >=2021.3.0
  run:
    - python >=3.7
    - numpy
    - pyusb
    - seabreeze
    - yaqd-core >=2021.3.0

test:
  imports:
    - yaqd_seabreeze
  commands:
    - pip check
    - yaqd-seabreeze --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for Ocean Optics SeaBreeze spectrometers.
  dev_url: https://gitlab.com/yaq/yaqd-seabreeze
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
